[project]
name = "trading-terminal"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "PaoloV99", email = "140324664+PaoloV99@users.noreply.github.com" }
]
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.141.1",
    "pyserial>=3.5",
    "uvicorn>=0.52.1",
    "websockets>=17.0.1",
]
